server:
  port: 8080

spring:
  banner:
    location: classpath:banner.txt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/java_school?useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true


logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug